### ISSUE TITLE
Tooltip data as call-tips

### ISSUE THREAD

**Issue by johnbillion** [php-integrator/atom-call-tips-legacy-php56#11]
The tooltips package provides the information I want, and the call-tips package provides it at the time I want it, but there's no way to get the best of both worlds.

What I'd like to see is the full docblock data that's available in tooltips, but displayed as a call-tip when my cursor is inside the function's brackets.

It'd be great to see this as an option.

**Comment by Gert-dev** [comment]
I have to admit that I sometimes have the same feeling. I also vaguely recall some IDE (Visual Studio or perhaps Eclipse?) showing a minimal call tip by default and allowing you to press a shortcut afterwards (e.g. ctrl + space) to expand the call tip with more information.

I don't think providing the option to expand the call tip will harm anyone, so I could implement that as a base and then add a package setting to always expand by default.

**Comment by Gert-dev** [comment]
I'm moving all relevant tickets from this repository to the base package as this functionality is now part of the base package.

See also https://github.com/php-integrator/atom-base/issues/301 .
