### ISSUE TITLE
Way to hide when not mousing over

### ISSUE THREAD

**Issue by mrthebob** [php-integrator/atom-call-tips-legacy-php56#12]
The call tip tends to get in the way while I'm programming. It provides very useful information, but I often need to see things underneath it. I'd very much love it if it would work on mouse over. That is, the tip shows when I mouse over, but when the mouse isn't there - no tip, so that I can work and see everything I need.

Love the plugin. Very useful.

Thanks!

**Comment by Gert-dev** [comment]
Thanks for the suggestion. I've encountered the same problem and have been wondering for a while about what a good solution would be.

I believe PhpStorm doesn't immediately trigger the call tip, like php-integrator does. It seems to have some kind of more intelligent system where it only shows the tooltip when you first start typing the function (not too sure about how it works, exactly), combined with being able to manually summon it with a keyboard shortcut.

I like how it's currently always there when you need it, but I dislike how it's on top of everything. Your suggestion to use the mouse could work, but I'm afraid this will negatively affect users that rarely use the mouse.

**Comment by mrthebob** [comment]
Perhaps 2 things?

1. an /option/ that is off by default that allows the mouse solution above
2. a key command to turn the tooltips off or on

**Comment by Gert-dev** [comment]
If I understand you correctly, when you move the keyboard cursor inside a function/method call, you only see the call tip if the mouse is also _on_ the same function/method call?

I think this is something that can be accomplished, but won't having your mouse on the function/method call obstruct your view of what you're typing?

Also, you would have to always move the mouse somewhere at the start of the call, as if you place it to the right, then delete an argument or a few characters (causing the mouse to now fall just outside the call), the call tip would suddenly disappear.

**Comment by mrthebob** [comment]
Well, not quite. I was offering two different potential solutions:

1. Mouse-only operation: call tips only appear for the function the mouse is currently hovering over. This would disregard keyboard position. Also - this would be a setting that defaults to "off". 

2. A key command that allows the user to turn on or off the call tips as they currently exists.

Another option I just thought of:

3. The plugin works as it does currently, except that when the user starts typing, the call tip disappears. When they stop typing (after a small delay), the call tips appear again.

Random question: how do other IDEs handle call tips?

**Comment by Gert-dev** [comment]
I remember how Visual Studio did it back in the day (though that was probably around 2005 or 2008): it's much the same as is currently done in this package, with the same downside.

As mentioned, I believe PhpStorm doesn't immediately trigger the call tip. It seems to have some kind of more intelligent system where it only shows the tooltip when you first start typing the function (not too sure about how it works, exactly), combined with being able to manually summon it with a keyboard shortcut.

I like how PhpStorm handles it, but having to request this information manually every time feels a bit counter-intuitive for call tips. It seems to make them a bit unnecessary as you already have the same information. and more, available via tooltips that display on mouse hover or, in 3.0, are triggered via a keyboard combination.

Maybe there is a better solution available that we haven't thought of. I see that [this package](https://atom.io/packages/go-signature-statusbar) experiments with moving the call tips to the status bar. This would certainly solve the problem of it obfuscating code as well as keeping it available at all times. However, I'd likely have to severely limit the available information, as signatures can be virtually infinite in length and the status bar has limited space.

**Comment by mrthebob** [comment]
That's an interesting possibility. What if... it were in the status bar,
but you could click on it to have it open up a panel that contained more
information for longer signatures? Kind of like the linter package?

**Comment by Gert-dev** [comment]
I'm moving all relevant tickets from this repository to the base package as this functionality is now part of the base package.
